/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as IndexImport } from './routes/index'
import { Route as BonusIndexImport } from './routes/bonus/index'
import { Route as ContractContractIdImport } from './routes/contract/$contractId'

// Create/Update Routes

const IndexRoute = IndexImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const BonusIndexRoute = BonusIndexImport.update({
  path: '/bonus/',
  getParentRoute: () => rootRoute,
} as any)

const ContractContractIdRoute = ContractContractIdImport.update({
  path: '/contract/$contractId',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/contract/$contractId': {
      preLoaderRoute: typeof ContractContractIdImport
      parentRoute: typeof rootRoute
    }
    '/bonus/': {
      preLoaderRoute: typeof BonusIndexImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export const routeTree = rootRoute.addChildren([
  IndexRoute,
  ContractContractIdRoute,
  BonusIndexRoute,
])

/* prettier-ignore-end */
